name: Load users

on:
  workflow_dispatch:
    inputs:
      github_organization:
        description: 'GitHub Organization Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bypass Cloudflare for GitHub Action
        uses: xiaotianxt/bypass-cloudflare-for-github-action@v1.0.0
        with:
          cf_zone_id: ${{ secrets.CF_ZONE_ID }}
          cf_api_key: ${{ secrets.CF_API_KEY }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run Rust Program
        run: cargo run --release
        env:
          GITHUB_ORGANIZATION: ${{ github.event.inputs.github_organization }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUES_API: ${{ vars.ISSUES_API }}
          ISSUES_API_TOKEN: ${{ secrets.ISSUES_API_TOKEN }}
